runtime: python37 #python27
service: my-app
instance_class: F4
automatic_scaling:
    target_cpu_utilization: 0.85
    min_instances: 0
    max_instances: 3
    # min_pending_latency: 30ms
    max_pending_latency: 9000ms
    max_concurrent_requests: 1000